#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-String-CRC32
Version  : 1.6
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/L/LE/LEEJO/String-CRC32-1.6.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/L/LE/LEEJO/String-CRC32-1.6.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libs/libstring-crc32-perl/libstring-crc32-perl_1.6-1.debian.tar.xz
Summary  : unknown
Group    : Development/Tools
License  : unrestricted
Requires: perl-String-CRC32-lib
Requires: perl-String-CRC32-man

%description
# NAME
String::CRC32 - Perl interface for cyclic redundancy check generation
# SYNOPSIS

%package lib
Summary: lib components for the perl-String-CRC32 package.
Group: Libraries

%description lib
lib components for the perl-String-CRC32 package.


%package man
Summary: man components for the perl-String-CRC32 package.
Group: Default

%description man
man components for the perl-String-CRC32 package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n String-CRC32-1.6
mkdir -p %{_topdir}/BUILD/String-CRC32-1.6/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/String-CRC32-1.6/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/String/CRC32.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/String/CRC32.pod

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/String/CRC32/CRC32.so

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/String::CRC32.3
